//User actions
export const ADD_USER_REQUEST = 'ADD_USER_REQUEST';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER = 'UPDATE_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//Project actions
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_REDIRECT = 'PROJECT_REDIRECT';
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const REMOVE_PROJECT_REQUEST = 'REMOVE_PROJECT_REQUEST';
export const REMOVE_PROJECT = 'REMOVE PROJECT';
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';

//Card actions
export const ADD_CARD_REQUEST = 'ADD_CARD_REQUEST';
export const ADD_CARD = 'ADD_CARD';
export const UPDATE_CARD_REQUEST = 'UPDATE_CARD_REQUEST';
export const UPDATE_CARD = 'UPDATE_CARD';
export const REMOVE_CARD_REQUEST = 'REMOVE_CARD_REQUEST';
export const REMOVE_CARD = 'REMOVE_CARD';
export const FETCH_PROJECT_CARDS = 'FETCH_PROJECT_CARDS';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';

//Task actions
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST';
export const UPDATE_TASK = 'UPDATE_TASK';
export const REMOVE_TASK_REQUEST = 'REMOVE_TASK_REQUEST';
export const REMOVE_TASK = 'REMOVE_TASK';
export const MOVE_TASK_REQUEST = 'MOVE_TASK_REQUEST';
export const MOVE_TASK = 'MOVE_TASK';

//UI actions
export const ACTIVATE_MODAL = 'ACTIVATE_MODAL';
export const DEACTIVATE_MODAL = 'DEACTIVATE_MODAL';
export const SET_STATUS_FILTER = 'SET_STATUS_FILTER';

//Authentication actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';